### ISSUE TITLE
1.1.0 で test/deferred_test.rb が失敗する

### ISSUE THREAD

**Issue by dai-vdr** [toshia/delayer-deferred#4]
https://github.com/toshia/delayer-deferred/blob/v1.1.0/test/deferred_test.rb#L239-L240

failure.process が nil になっているようです。

```
# Running:

..E......................../var/local/deb/ruby-delayer-deferred/ruby-delayer-deferred/test/enumerable_test.rb:34:in `block (3 levels) in <top (required)>': Object#timeout is deprecated, use Timeout.timeout instead.
..

Finished in 0.219445s, 132.1516 runs/s, 346.3283 assertions/s.

  1) Error:
Delayer::Deferred::Deferredable#system#test_0002_command failed:
NoMethodError: undefined method `exited?' for nil:NilClass
Did you mean?  extend
    /var/local/deb/ruby-delayer-deferred/ruby-delayer-deferred/test/deferred_test.rb:239:in `block (3 levels) in <top (required)>'
```

**Comment by toshia** [comment]
1.1.1 で修正しました

**Comment by dai-vdr** [comment]
ありがとうございます。修正を確認しました。
