### ISSUE TITLE
Ruby 2.6.5でDeferred.when()を使うとエラーが発生する

### ISSUE THREAD

**Issue by shibafu528** [toshia/delayer-deferred#5]
Ruby 2.6.5, delayer-deferred 2.1.2の組み合わせで `Deferred.when()` を使用すると、常にTypeErrorが発生します。  
Ruby 2.7.0では発生しません。

おそらく、下記の部分のkwrestの扱いだとは思うのですが……

https://github.com/toshia/delayer-deferred/blob/acdf6764b73f2d116f65149b795df4e7e7e3a5ce/lib/delayer/deferred.rb#L21-L23

## Ruby version
`ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]`

## Trace
```
Traceback (most recent call last):
        18: from mikutter.rb:117:in `<main>'
        17: from mikutter.rb:81:in `boot!'
        16: from /home/shibafu/git/mikutter/plugin/gtk/mainloop.rb:10:in `mainloop'
        15: from /home/shibafu/git/mikutter/plugin/gtk/mainloop.rb:10:in `catch'
        14: from /home/shibafu/git/mikutter/plugin/gtk/mainloop.rb:12:in `block in mainloop'
        13: from /home/shibafu/git/mikutter/plugin/gtk/mainloop.rb:12:in `loop'
        12: from /home/shibafu/git/mikutter/plugin/gtk/mainloop.rb:23:in `block (2 levels) in mainloop'
        11: from /home/shibafu/git/mikutter/vendor/bundle/ruby/2.6.0/gems/delayer-1.1.1/lib/delayer.rb:37:in `method_missing'
        10: from /home/shibafu/git/mikutter/vendor/bundle/ruby/2.6.0/gems/delayer-1.1.1/lib/delayer/extend.rb:102:in `run_once'
         9: from /home/shibafu/git/mikutter/vendor/bundle/ruby/2.6.0/gems/delayer-1.1.1/lib/delayer/procedure.rb:26:in `run'
         8: from /home/shibafu/git/mikutter/plugin/mastodon/mastodon.rb:67:in `block (2 levels) in <top (required)>'
         7: from /home/shibafu/git/mikutter/plugin/mastodon/mastodon.rb:51:in `block (2 levels) in <top (required)>'
         6: from /home/shibafu/git/mikutter/plugin/mastodon/mastodon.rb:51:in `each'
         5: from /home/shibafu/git/mikutter/plugin/mastodon/mastodon.rb:52:in `block (3 levels) in <top (required)>'
         4: from /home/shibafu/git/mikutter/vendor/bundle/ruby/2.6.0/gems/delayer-deferred-2.1.2/lib/delayer/deferred.rb:22:in `method_missing'
         3: from /home/shibafu/git/mikutter/vendor/bundle/ruby/2.6.0/gems/delayer-deferred-2.1.2/lib/delayer/deferred/tools.rb:37:in `when'
         2: from /home/shibafu/git/mikutter/vendor/bundle/ruby/2.6.0/gems/delayer-deferred-2.1.2/lib/delayer/deferred/tools.rb:37:in `each_with_index'
         1: from /home/shibafu/git/mikutter/vendor/bundle/ruby/2.6.0/gems/delayer-deferred-2.1.2/lib/delayer/deferred/tools.rb:37:in `each'
/home/shibafu/git/mikutter/vendor/bundle/ruby/2.6.0/gems/delayer-deferred-2.1.2/lib/delayer/deferred/tools.rb:39:in `block in when': Argument 3 of Deferred.when must be Delayer::Deferred::Deferredable::Chainable, but given Hash (TypeError)
```

**Comment by toshia** [comment]
対応しました！

**Comment by shibafu528** [comment]
問題を起こしていた環境にて、動作することが確認できました。ありがとうございます。

**Comment by toshia** [comment]
thx
